"""FRIDAY service (baseline §3.3).

FRIDAY is the file-management and operations agent.
Executes real filesystem operations on disk within the project workspace:
- Creates files and directories dynamically based on command input.
- Organizes loose files into categorized subfolders.
- Reads and lists directory manifests.
"""

from __future__ import annotations

import os
import re
import shutil
from pathlib import Path

# Workspace base directory for safe operations
WORKSPACE_DIR = Path("d:/Agent/edith/work")

CATEGORY_MAP = {
    ".txt": "documents",
    ".pdf": "documents",
    ".doc": "documents",
    ".docx": "documents",
    ".md": "documents",
    ".py": "code",
    ".js": "code",
    ".ts": "code",
    ".html": "code",
    ".css": "code",
    ".json": "data",
    ".csv": "data",
    ".xml": "data",
    ".png": "images",
    ".jpg": "images",
    ".jpeg": "images",
    ".gif": "images",
    ".zip": "archives",
    ".tar": "archives",
    ".gz": "archives",
}


def _ensure_workspace() -> Path:
    WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)
    return WORKSPACE_DIR


def organize_directory(target_path: Path) -> dict:
    """Organize loose files in target_path into category folders."""
    target_path.mkdir(parents=True, exist_ok=True)

    files_processed = 0
    dirs_created = set()
    moved_manifest = []

    for entry in target_path.iterdir():
        if entry.is_file():
            ext = entry.suffix.lower()
            category = CATEGORY_MAP.get(ext, "misc")
            category_dir = target_path / category
            category_dir.mkdir(exist_ok=True)
            dirs_created.add(category)

            dest = category_dir / entry.name
            shutil.move(str(entry), str(dest))
            files_processed += 1
            moved_manifest.append(f"{entry.name} -> {category}/{entry.name}")

    return {
        "action": "organize",
        "target_directory": str(target_path),
        "files_processed": files_processed,
        "directories_created": list(dirs_created),
        "manifest": moved_manifest,
    }


def execute(command: str) -> dict:
    """Execute real file management operations on disk."""
    ws = _ensure_workspace()
    text = command.lower()

    # 1. Dynamic File Creation Request (e.g. "create file test.txt", "make file notes.md")
    create_match = re.search(r"(?:create|make|write|add)\s+(?:a\s+)?file\s+([\w\.\-]+)", text)
    if create_match:
        filename = create_match.group(1)
        file_path = ws / filename
        content = f"File '{filename}' generated by FRIDAY agent for command: '{command}'\n"
        file_path.write_text(content, encoding="utf-8")
        return {
            "agent": "FRIDAY",
            "kind": "file_management",
            "mock": False,
            "command": command,
            "summary": f"FRIDAY created file '{filename}' at '{file_path}'.",
            "plan": [
                f"Resolved target path: '{file_path}'",
                f"Created file with size {len(content)} bytes.",
                "Verified disk write operation.",
            ],
            "details": {
                "action": "create_file",
                "file_path": str(file_path),
                "bytes_written": len(content),
                "status": "Success",
            },
        }

    # 2. Dynamic Directory Creation Request (e.g. "create folder reports", "make directory docs")
    dir_match = re.search(r"(?:create|make|add)\s+(?:a\s+)?(?:folder|directory)\s+([\w\.\-]+)", text)
    if dir_match:
        foldername = dir_match.group(1)
        folder_path = ws / foldername
        folder_path.mkdir(parents=True, exist_ok=True)
        return {
            "agent": "FRIDAY",
            "kind": "file_management",
            "mock": False,
            "command": command,
            "summary": f"FRIDAY created directory '{foldername}' at '{folder_path}'.",
            "plan": [
                f"Resolved folder path: '{folder_path}'",
                "Created directory entry on filesystem.",
                "Verified directory structure.",
            ],
            "details": {
                "action": "create_directory",
                "folder_path": str(folder_path),
                "status": "Success",
            },
        }

    # 3. Organize Request
    if any(k in text for k in ["organize", "organise", "group", "folder", "sort"]):
        existing_files = [f for f in ws.iterdir() if f.is_file()]
        if not existing_files:
            sample_files = ["report.txt", "notes.md", "data.json", "script.py", "diagram.png"]
            for sf in sample_files:
                (ws / sf).write_text(f"Sample content for {sf}\n", encoding="utf-8")

        result_data = organize_directory(ws)
        return {
            "agent": "FRIDAY",
            "kind": "file_management",
            "mock": False,
            "command": command,
            "summary": (
                f"FRIDAY organized {result_data['files_processed']} file(s) in "
                f"'{result_data['target_directory']}' into {len(result_data['directories_created'])} subfolders."
            ),
            "plan": [
                f"Inspected directory: '{result_data['target_directory']}'",
                f"Grouped files into categories: {', '.join(result_data['directories_created']) or 'existing folders'}",
                f"Processed and moved {result_data['files_processed']} files.",
                "Verified directory structure and completed file operations."
            ],
            "details": result_data,
        }

    # 4. Default Directory Inspection & File List
    items = [f.name for f in ws.rglob("*")]
    return {
        "agent": "FRIDAY",
        "kind": "file_management",
        "mock": False,
        "command": command,
        "summary": f"FRIDAY inspected workspace '{ws}' containing {len(items)} item(s).",
        "plan": [
            f"Accessed workspace directory: '{ws}'",
            "Read file manifest and structure.",
            "Prepared operational state.",
        ],
        "details": {"workspace": str(ws), "item_count": len(items), "items": items},
    }
