"""JARVIS service (baseline §3.1, §5.2).

JARVIS is the primary user-facing agent and the delegation decision-maker.
For this slice the decision is deterministic and rule-based (no LLM): JARVIS
classifies a command into a required capability, then:

- if the capability is one of JARVIS's own (coding/debugging/git/github/web),
  JARVIS handles it directly (coding is generated by the Coding Service via an
  LLM; other own-capabilities return a conversational reply for now);
- otherwise JARVIS chooses the target agent via the Agent Registry and
  returns a delegation decision for the Runtime to transport (§12).

JARVIS decides *whether* to delegate and *which* agent. The Runtime never
makes this semantic choice.
"""

from __future__ import annotations

from dataclasses import dataclass

from runtime.registry import AgentRegistry
from schemas.enums import AgentName, Capability
from services.coding_service import CodingService

# Deterministic keyword rules mapping to a required capability. Ordered by
# specificity; first match wins. This stands in for future LLM reasoning.
_KEYWORD_CAPABILITY: list[tuple[Capability, tuple[str, ...]]] = [
    (Capability.FILE_MANAGEMENT,
     ("file", "files", "folder", "directory", "organize", "organise",
      "rename", "move", "document")),
    (Capability.COMPUTER_CONTROL,
     ("screen", "mouse", "keyboard", "click", "open app", "application",
      "browser", "navigate", "computer")),
    (Capability.CODING,
     ("code", "coding", "program", "programming", "function", "class",
      "method", "algorithm", "script", "compile", "factorial", "bug",
      "debug", "git", "github", "api", "regex",
      # common programming languages / ecosystems
      "python", "javascript", "typescript", "java", "kotlin", "c++", "c#",
      "golang", "rust", "ruby", "php", "sql", "html", "css", "react",
      "swift")),
]


@dataclass
class Decision:
    """The outcome of JARVIS's routing decision."""

    capability: Capability | None       # None => plain conversation
    handled_directly: bool              # True => JARVIS does the work itself
    target_agent: AgentName             # who ultimately performs the work


class JarvisService:
    def __init__(self, registry: AgentRegistry, coding_service: CodingService) -> None:
        self._registry = registry
        self._coding = coding_service

    # --- decision -------------------------------------------------------
    def classify(self, command: str) -> Capability | None:
        text = command.lower()
        for capability, keywords in _KEYWORD_CAPABILITY:
            if any(k in text for k in keywords):
                return capability
        return None

    def decide(self, command: str) -> Decision:
        """Decide whether JARVIS handles the command or delegates it."""
        capability = self.classify(command)

        # Plain conversation, or a capability JARVIS itself owns -> direct.
        jarvis = self._registry.get(AgentName.JARVIS)
        if capability is None or jarvis.has_capability(capability):
            return Decision(
                capability=capability,
                handled_directly=True,
                target_agent=AgentName.JARVIS,
            )

        # Otherwise find the specialist agent for this capability.
        target = self._registry.find_by_capability(capability)
        if target is None:
            # No agent advertises this capability; JARVIS keeps it.
            return Decision(
                capability=capability,
                handled_directly=True,
                target_agent=AgentName.JARVIS,
            )
        return Decision(
            capability=capability,
            handled_directly=False,
            target_agent=target.name,
        )

    # --- direct execution ----------------------------------------------
    def handle_directly(self, command: str, capability: Capability | None) -> dict:
        """Produce JARVIS's own result for a directly-handled command.

        Coding requests are generated by the Coding Service (LLM-backed);
        anything else gets a conversational reply. The returned dict is stored
        as-is in ``Task.result``.
        """
        if capability == Capability.CODING:
            return self._coding.generate(command).model_dump()
        return {
            "agent": "JARVIS",
            "kind": "conversation",
            "mock": True,
            "command": command,
            "reply": "JARVIS acknowledges your request.",
        }
